import type { CourtDTO } from '@tennis/contracts';
import { IMG, U } from './images';

// 12 courts ported verbatim from the HTML prototypes (`map.html` COURTS array).
//
// Field translations from the prototype shape to the DTO shape:
//   coords  -> mapCoords        (screen [x%, y%] — NOT geo, Risk #17)
//   io      -> indoorOutdoor
//   locked  -> isLocked
//   scenic  -> isScenic
//   featured-> isFeatured
//
// `slug` is authored here (kebab/id form) as the routing + seed key (Risk #18).
// `lat`/`lng`/`approxLat`/`approxLng` are PLACEHOLDER real-geo values — they only
// need to exist and be geo-shaped in Phase 0; real coordinates are an editorial/
// seed concern for later. They are deliberately distinct from `mapCoords`.

type CourtSeed = Omit<CourtDTO, 'images' | 'heroImageUrl'> & {
  heroImageUrl: string;
  images: CourtDTO['images'];
};

export const COURTS: CourtSeed[] = [
  {
    id: 'tremezzo',
    slug: 'grand-hotel-tremezzo',
    name: 'Grand Hotel Tremezzo',
    country: 'Italy',
    region: 'Lake Como',
    surface: 'Clay',
    setting: 'Lakefront',
    access: 'Resort',
    indoorOutdoor: 'Outdoor',
    isScenic: true,
    isLocked: false,
    isFeatured: true,
    status: 'published',
    mapCoords: [49, 32],
    lat: 45.9876,
    lng: 9.2233,
    approxLat: 45.99,
    approxLng: 9.22,
    heroImageUrl: U(IMG.como),
    images: [
      { url: U(IMG.como), isHero: true, sortOrder: 0 },
      { url: U(IMG.courtAerial), isHero: false, sortOrder: 1 },
      { url: U(IMG.courtShadow), isHero: false, sortOrder: 2 },
      { url: U(IMG.clayCourt), isHero: false, sortOrder: 3 },
      { url: U(IMG.med), isHero: false, sortOrder: 4 },
    ],
    blurb:
      "Suspended above Lake Como's mirror-still water, the court at Grand Hotel Tremezzo is set within a century-old garden of cypress and bougainvillea. Players rally against a backdrop of the Grigne mountains and a horizon of pale stucco villas. After play, retreat to the lakeside terrace for a campari and the slow hours that follow.",
  },
  {
    id: 'tragara',
    slug: 'hotel-punta-tragara',
    name: 'Hotel Punta Tragara',
    country: 'Italy',
    region: 'Capri',
    surface: 'Hard',
    setting: 'Cliffside',
    access: 'Resort',
    indoorOutdoor: 'Outdoor',
    isScenic: true,
    isLocked: true,
    isFeatured: false,
    status: 'published',
    mapCoords: [54, 44],
    lat: 40.5489,
    lng: 14.2412,
    approxLat: 40.55,
    approxLng: 14.24,
    heroImageUrl: U(IMG.capri),
    images: [
      { url: U(IMG.capri), isHero: true, sortOrder: 0 },
      { url: U(IMG.med), isHero: false, sortOrder: 1 },
      { url: U(IMG.courtAerial), isHero: false, sortOrder: 2 },
    ],
    blurb:
      "A Le Corbusier-designed sanctuary on Capri's southern cliffs. The single court is cut into the rock above the Faraglioni — play opens to the Mediterranean and closes with limoncello in the garden bar.",
  },
  {
    id: 'mansour',
    slug: 'royal-mansour',
    name: 'Royal Mansour',
    country: 'Morocco',
    region: 'Marrakech',
    surface: 'Clay',
    setting: 'Walled garden',
    access: 'Resort',
    indoorOutdoor: 'Outdoor',
    isScenic: false,
    isLocked: true,
    isFeatured: true,
    status: 'published',
    mapCoords: [40, 56],
    lat: 31.6295,
    lng: -7.9811,
    approxLat: 31.63,
    approxLng: -7.98,
    heroImageUrl: U(IMG.morocco),
    images: [
      { url: U(IMG.morocco), isHero: true, sortOrder: 0 },
      { url: U(IMG.clayCourt), isHero: false, sortOrder: 1 },
      { url: U(IMG.courtShadow), isHero: false, sortOrder: 2 },
    ],
    blurb:
      "Inside the medina's terracotta walls, a court of rust-red clay shaded by ancient olive trees. Morning hours only — the heat takes the afternoon.",
  },
  {
    id: 'residencia',
    slug: 'belmond-la-residencia',
    name: 'Belmond La Residencia',
    country: 'Spain',
    region: 'Mallorca',
    surface: 'Clay',
    setting: 'Mountain village',
    access: 'Resort',
    indoorOutdoor: 'Outdoor',
    isScenic: true,
    isLocked: false,
    isFeatured: false,
    status: 'published',
    mapCoords: [44, 38],
    lat: 39.7491,
    lng: 2.6469,
    approxLat: 39.75,
    approxLng: 2.65,
    heroImageUrl: U(IMG.med),
    images: [
      { url: U(IMG.med), isHero: true, sortOrder: 0 },
      { url: U(IMG.clayCourt), isHero: false, sortOrder: 1 },
      { url: U(IMG.courtAerial), isHero: false, sortOrder: 2 },
    ],
    blurb:
      'Tucked into the Tramuntana mountains above Deià, two clay courts within an olive grove, the village church bells the only sound between points.',
  },
  {
    id: 'como',
    slug: 'como-shambhala-estate',
    name: 'Como Shambhala Estate',
    country: 'Indonesia',
    region: 'Bali',
    surface: 'Hard',
    setting: 'Jungle',
    access: 'Resort',
    indoorOutdoor: 'Outdoor',
    isScenic: true,
    isLocked: true,
    isFeatured: false,
    status: 'published',
    mapCoords: [78, 58],
    lat: -8.4767,
    lng: 115.2625,
    approxLat: -8.48,
    approxLng: 115.26,
    heroImageUrl: U(IMG.bali),
    images: [
      { url: U(IMG.bali), isHero: true, sortOrder: 0 },
      { url: U(IMG.courtShadow), isHero: false, sortOrder: 1 },
    ],
    blurb:
      'Cut into the Ayung river gorge near Ubud. The court is reached by a stone path through frangipani; macaques watch from the canopy.',
  },
  {
    id: 'nell',
    slug: 'the-little-nell',
    name: 'The Little Nell',
    country: 'USA',
    region: 'Aspen',
    surface: 'Hard',
    setting: 'Alpine',
    access: 'Resort',
    indoorOutdoor: 'Outdoor',
    isScenic: true,
    isLocked: false,
    isFeatured: false,
    status: 'published',
    mapCoords: [18, 36],
    lat: 39.1872,
    lng: -106.8175,
    approxLat: 39.19,
    approxLng: -106.82,
    heroImageUrl: U(IMG.aspen),
    images: [
      { url: U(IMG.aspen), isHero: true, sortOrder: 0 },
      { url: U(IMG.courtAerial), isHero: false, sortOrder: 1 },
    ],
    blurb:
      'Aspen Mountain rises directly behind the baseline. Summer mornings smell of pine; the altitude lifts the ball an extra foot.',
  },
  {
    id: 'cheval',
    slug: 'cheval-blanc-randheli',
    name: 'Cheval Blanc Randheli',
    country: 'Maldives',
    region: 'Noonu Atoll',
    surface: 'Hard',
    setting: 'Island',
    access: 'Private',
    indoorOutdoor: 'Outdoor',
    isScenic: true,
    isLocked: true,
    isFeatured: true,
    status: 'published',
    mapCoords: [70, 60],
    lat: 5.6634,
    lng: 73.3502,
    approxLat: 5.66,
    approxLng: 73.35,
    heroImageUrl: U(IMG.maldives),
    images: [
      { url: U(IMG.maldives), isHero: true, sortOrder: 0 },
      { url: U(IMG.courtAerial), isHero: false, sortOrder: 1 },
    ],
    blurb:
      'An island unto itself. The court sits between two reef-edges, lit at dusk by lanterns staked into the sand.',
  },
  {
    id: 'aman',
    slug: 'aman-tokyo',
    name: 'Aman Tokyo',
    country: 'Japan',
    region: 'Otemachi',
    surface: 'Hard',
    setting: 'Rooftop',
    access: 'Resort',
    indoorOutdoor: 'Indoor',
    isScenic: false,
    isLocked: true,
    isFeatured: false,
    status: 'published',
    mapCoords: [82, 38],
    lat: 35.6877,
    lng: 139.7664,
    approxLat: 35.69,
    approxLng: 139.77,
    heroImageUrl: U(IMG.tokyo),
    images: [
      { url: U(IMG.tokyo), isHero: true, sortOrder: 0 },
      { url: U(IMG.courtAerial), isHero: false, sortOrder: 1 },
    ],
    blurb:
      'On the 33rd floor of the Otemachi tower, a private court rises above the imperial gardens. Wash basins of warm cedar at the door.',
  },
  {
    id: 'soho',
    slug: 'soho-farmhouse',
    name: 'Soho Farmhouse',
    country: 'UK',
    region: 'Cotswolds',
    surface: 'Grass',
    setting: 'Countryside',
    access: 'Club',
    indoorOutdoor: 'Outdoor',
    isScenic: false,
    isLocked: false,
    isFeatured: false,
    status: 'published',
    mapCoords: [47, 28],
    lat: 51.9426,
    lng: -1.5258,
    approxLat: 51.94,
    approxLng: -1.53,
    heroImageUrl: U(IMG.cotswolds),
    images: [
      { url: U(IMG.cotswolds), isHero: true, sortOrder: 0 },
      { url: U(IMG.courtAerial), isHero: false, sortOrder: 1 },
    ],
    blurb:
      "Mown stripes, white linens, an honesty bar of Pimm's. The grass court at Soho Farmhouse keeps an English summer to itself.",
  },
  {
    id: 'monte',
    slug: 'monte-carlo-country-club',
    name: 'Monte-Carlo Country Club',
    country: 'Monaco',
    region: 'Roquebrune',
    surface: 'Clay',
    setting: 'Cliffside',
    access: 'Club',
    indoorOutdoor: 'Outdoor',
    isScenic: true,
    isLocked: true,
    isFeatured: false,
    status: 'published',
    mapCoords: [50, 40],
    lat: 43.7508,
    lng: 7.4386,
    approxLat: 43.75,
    approxLng: 7.44,
    heroImageUrl: U(IMG.courtAerial),
    images: [
      { url: U(IMG.courtAerial), isHero: true, sortOrder: 0 },
      { url: U(IMG.clayCourt), isHero: false, sortOrder: 1 },
    ],
    blurb:
      'The terraced clay courts of Roquebrune face the Mediterranean head-on. Cypress hedges, white umbrellas, the Masters in April.',
  },
  {
    id: 'sixsenses',
    slug: 'six-senses-douro',
    name: 'Six Senses Douro',
    country: 'Portugal',
    region: 'Douro Valley',
    surface: 'Clay',
    setting: 'Vineyard',
    access: 'Resort',
    indoorOutdoor: 'Outdoor',
    isScenic: true,
    isLocked: true,
    isFeatured: false,
    status: 'published',
    mapCoords: [42, 38],
    lat: 41.1579,
    lng: -7.7864,
    approxLat: 41.16,
    approxLng: -7.79,
    heroImageUrl: U(IMG.clayCourt),
    images: [
      { url: U(IMG.clayCourt), isHero: true, sortOrder: 0 },
      { url: U(IMG.med), isHero: false, sortOrder: 1 },
    ],
    blurb:
      'A clay court terraced into a 19th-century vineyard above the Douro. Play before the heat, port at dusk.',
  },
  {
    id: 'edenroc',
    slug: 'hotel-du-cap-eden-roc',
    name: 'Hotel du Cap-Eden-Roc',
    country: 'France',
    region: 'Antibes',
    surface: 'Clay',
    setting: 'Coastal',
    access: 'Resort',
    indoorOutdoor: 'Outdoor',
    isScenic: true,
    isLocked: true,
    isFeatured: false,
    status: 'published',
    mapCoords: [51, 42],
    lat: 43.5519,
    lng: 7.115,
    approxLat: 43.55,
    approxLng: 7.12,
    heroImageUrl: U(IMG.med),
    images: [
      { url: U(IMG.med), isHero: true, sortOrder: 0 },
      { url: U(IMG.clayCourt), isHero: false, sortOrder: 1 },
    ],
    blurb:
      "Five clay courts on the Cap d'Antibes, pine-shaded and salt-aired. The kind of place where time collapses gracefully.",
  },
];
